# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-15 18:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=50, verbose_name='Airport Name')),
                ('airport_locid', models.CharField(max_length=3, verbose_name='LOCID')),
                ('ado_pm', models.CharField(max_length=20, verbose_name='Ado Program Manager')),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_number', models.CharField(max_length=200, verbose_name='Grant Number')),
                ('grant_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Grant Amount')),
                ('airport', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='grant.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_description', models.CharField(max_length=200, verbose_name='Project Description')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grant.Grant')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=200, verbose_name='Report Type')),
                ('report_doc', models.FileField(default=None, upload_to='uploads/')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grant.Grant')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(blank=True, default=None, max_length=200, verbose_name='Sponsor Name')),
                ('sponsor_type', models.CharField(blank=True, default=None, max_length=200, verbose_name='Sponsor Type')),
                ('sponsor_addr1', models.CharField(blank=True, default=None, max_length=200, verbose_name='Sponsor Address 1')),
                ('sponsor_addr2', models.CharField(blank=True, default=None, max_length=200, verbose_name='Sponsor Address 2')),
                ('sponsor_addr3', models.CharField(blank=True, default=None, max_length=200, verbose_name='Sponsor Address 3')),
                ('sponsor_city', models.CharField(blank=True, default=None, max_length=200, verbose_name='Sponsor City')),
                ('sponsor_state', models.CharField(blank=True, default=None, max_length=200, verbose_name='Sponsor State')),
                ('sponsor_zip', models.CharField(blank=True, default=None, max_length=200, verbose_name='Sponsor Zip')),
                ('sponsor_county', models.CharField(blank=True, default=None, max_length=200, verbose_name='Sponsor County')),
                ('sponsor_DUN', models.IntegerField(blank=True, null=True, verbose_name='DUN Number')),
                ('sponsor_ADO', models.CharField(blank=True, default=None, max_length=200, verbose_name='ADO')),
                ('airport', models.ManyToManyField(to='grant.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default='')),
                ('phone', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
