# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-26 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grant', '0002_auto_20181026_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='airport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grant.Airport'),
            preserve_default=False,
        ),
    ]
